version: '3'

services:
  mongodb: #어플리케이션 설정
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO-INITDB_ROOT_USERNAME=admin
      - MONGO-INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-network

  mongo-express: #어플리케이션 설정
    image: mongo-express
    ports:
      - 8080:8080
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-network


networks:
  mongo-network:


# volumes:
#   # 볼륨 설정